### ISSUE TITLE
Parte3: Criar interface web para as funcionalidades da API (Bootstrap, webpack, handlebars)

### ISSUE THREAD

**Issue by hugocarv** [SerBasti/PI-1920i-LI52D-G04#11]
- Listagem de jogos populares
 - Pesquisa de jogo por nome
 - Listagem de grupos
 - Detalhe de grupo

>[Criar uma interface Web para apresentação num web browser, para todas as funcionalidades disponibilizadas pela Web API. Na criação desta interface devem ser usadas as tecnologias: HTML, CSS, Bootstrap framework, webpack fetch e Handlebars.](https://github.com/isel-leic-pi/PI-1920i-LI52D/wiki/PI-1920-2-Trab-P2&3#requisitos-funcionais-e-n%C3%A3o-funcionais-1)

**Comment by hugocarv** [comment]
### Roadmap:

**Grupos:**
- [ ] Cliente: Listagem de grupos com botão para editar e remover grupo
- [ ] Cliente: Detalhe do grupo
- [ ] Cliente: Formulário para adicionar grupo
- [ ] Cliente: Eventos para adicionar grupo ao clicar no botão
- [ ] Cliente: Eventos para editar grupo ao clicar no botão
- [ ] Cliente: Eventos para remover grupo ao clicar no botão

**Listagem de jogos populares:**
- [ ] Cliente: Listagem de jogos
- [ ] Cliente: Detalhe do jogo
