### ISSUE TITLE
Parte3: Registo e autenticação de utilizadores (Passport)

### ISSUE THREAD

**Issue by hugocarv** [SerBasti/PI-1920i-LI52D-G04#12]
- Formulário para registo e autenticação
 - Restrição de certas funcionalidades apenas a utilziadores autenticados

Enunciado:
>[2. Adicione à aplicação CIBORG a funcionalidade de registo e autenticação de utilizadores. Todas as funcionalidades de gestão de grupos de jogos devem estar acessíveis apenas a utilizadores autenticados. Os grupos são privados a cada utilizador e só podem ser manipulados pelo seu detentor (dono). Na implementação desta funcionalidade deve ser utilizado o módulo Passport.](https://github.com/isel-leic-pi/PI-1920i-LI52D/wiki/PI-1920-2-Trab-P2&3#requisitos-funcionais-e-n%C3%A3o-funcionais-1)

**Comment by hugocarv** [comment]
### Roadmap:

**Autenticação:**
- [ ] Cliente: Página de Login
- [ ] Cliente: Página de Registo
- [ ] Servidor: Implementar autenticação e as suas rotas do lado do servidor
- [ ] Servidor: Restringir determinadas partes do site a utilizadores registados
- [ ] Servidor: Criar novo index na DB ElasticSearch para utilizadores criados
