### ISSUE TITLE
Parte3: Gestão de grupos de cada utilizador

### ISSUE THREAD

**Issue by hugocarv** [SerBasti/PI-1920i-LI52D-G04#13]
- Adicionar e remover jogo de grupo
  - Criar, actualizar e remover Grupo

Enunciado:
>[2. Adicione à aplicação CIBORG a funcionalidade de registo e autenticação de utilizadores. Todas as funcionalidades de gestão de grupos de jogos devem estar acessíveis apenas a utilizadores autenticados. **Os grupos são privados a cada utilizador e só podem ser manipulados pelo seu detentor (dono)**. Na implementação desta funcionalidade deve ser utilizado o módulo Passport.](https://github.com/isel-leic-pi/PI-1920i-LI52D/wiki/PI-1920-2-Trab-P2&3#requisitos-funcionais-e-n%C3%A3o-funcionais-1)

**Comment by hugocarv** [comment]
### Roadmap:
**Grupos para utilizadores autenticados:**

- [ ] Cliente: Evento para adicionar jogo a um grupo [Após alterar/criar index para users na DB]
- [ ] Cliente: Listar grupos do utilizador
- [ ] Cliente: Ver jogos de um grupo do utilizador
